add options for devmapper

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3726,7 +3726,6 @@ $SI_MSG
 fi
 
 
-
 # where is python
 # Extract the first word of "python2", so it can be a program name with args.
 set dummy python2; ac_word=$2
@@ -3807,6 +3806,102 @@ echo "${ECHO_T}no" >&6
 fi
 
 PYTHON_PATH=$python_exec
+
+
+# do we have devmapper
+echo "$as_me:$LINENO: checking for dm_task_run in -llibdevmapper" >&5
+echo $ECHO_N "checking for dm_task_run in -llibdevmapper... $ECHO_C" >&6
+if test "${ac_cv_lib_libdevmapper_dm_task_run+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-llibdevmapper  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char dm_task_run ();
+int
+main ()
+{
+dm_task_run ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_libdevmapper_dm_task_run=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_libdevmapper_dm_task_run=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_libdevmapper_dm_task_run" >&5
+echo "${ECHO_T}$ac_cv_lib_libdevmapper_dm_task_run" >&6
+if test $ac_cv_lib_libdevmapper_dm_task_run = yes; then
+  have_libdevmapper=yes
+else
+
+    SI_MSG=`echo -e "- libdevmapper not found!\n"`
+    if test "x" != "x"; then
+        SI_MSG=`echo -e "$SI_MSG\n- "`
+    fi
+    if test "xlibdevmapper-devel" != "x"; then
+        SI_MSG=`echo -e "$SI_MSG\n- Try installing the libdevmapper-devel package\n"`
+    fi
+    if test "x" != "x"; then
+        SI_MSG=`echo -e "$SI_MSG\n- or get the latest software from \n"`
+    fi
+
+    { { echo "$as_me:$LINENO: error: !
+************************************************************
+$SI_MSG
+************************************************************
+" >&5
+echo "$as_me: error: !
+************************************************************
+$SI_MSG
+************************************************************
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+
+fi
 
 
 # do we have docbook, if not say know
