add check for flex, and fail if it isn't there

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3180,6 +3180,33 @@ _ACEOF
 fi
 
 fi
+case $LEX in
+    :)
+    SI_MSG=`echo -e "- lex not found!\n"`
+    if test "x" != "xYou can't build many components without the flex parser"; then
+        SI_MSG=`echo -e "$SI_MSG\n- You can't build many components without the flex parser"`
+    fi
+    if test "xflex" != "x"; then
+        SI_MSG=`echo -e "$SI_MSG\n- Try installing the flex package\n"`
+    fi
+    if test "x" != "x"; then
+        SI_MSG=`echo -e "$SI_MSG\n- or get the latest software from \n"`
+    fi
+
+    { { echo "$as_me:$LINENO: error: !
+************************************************************
+$SI_MSG
+************************************************************
+" >&5
+echo "$as_me: error: !
+************************************************************
+$SI_MSG
+************************************************************
+" >&2;}
+   { (exit 1); exit 1; }; }
+
+;;
+esac
 # Find a good install program.  We prefer a C program (faster),
 # so one script is as good as another.  But avoid the broken or
 # incompatible versions:
