Do udp-receiver --pipe /tmp/tar_cmd.sh

diff --git a/initrd_source/skel/etc/init.d/functions b/initrd_source/skel/etc/init.d/functions
--- a/initrd_source/skel/etc/init.d/functions
+++ b/initrd_source/skel/etc/init.d/functions
@@ -250,12 +250,16 @@ flamethrower_client() {
         echo "flamethrower_client(${MODULE_NAME})"
         echo '--------------------------------------------------------------------------------'
         echo "udp-receiver $UDP_RECEIVER_OPTIONS --pipe 'tar ${TAR_OPTS} -C ${DIR}'"
-        set -x
-        udp-receiver $UDP_RECEIVER_OPTIONS --pipe \'"tar ${TAR_OPTS} -C ${DIR}"\'
+        # Create script to do tar stuff.  Can't seem to get the tar command escaped properly for direct use 
+        # with --pipe.  For example, --pipe 'tar --overwrite -xp -C  /tmp/.flamethrower.12298' fails. -BEF-
+        echo "#!/bin/sh"                    > /tmp/tar_cmd.sh
+        echo "tar ${TAR_OPTS} -C ${DIR}"    >> /tmp/tar_cmd.sh
+        echo "exit $?"                      >> /tmp/tar_cmd.sh
+        chmod 755 /tmp/tar_cmd.sh
+set -x
+        udp-receiver $UDP_RECEIVER_OPTIONS --pipe /tmp/tar_cmd.sh
         UDP_RECEIVER_EXIT_STATUS=$?
-        set +x
-
-# XXX may need to tweak the above command
+set +x
 
         # proceed or retry based on exit status
         if [ "$UDP_RECEIVER_EXIT_STATUS" != "0" ]; then
