flamethrower_client_new() and flamethrower_client() from 3.1.4.  Also fix ETHER_SLEEP trap, so that you can actually break out of the code past that point.

diff --git a/initrd_source/skel/etc/init.d/functions b/initrd_source/skel/etc/init.d/functions
--- a/initrd_source/skel/etc/init.d/functions
+++ b/initrd_source/skel/etc/init.d/functions
@@ -134,7 +134,7 @@ count_loop() {
 
   COUNT=$1
 
-  trap 'echo "Skipping ETHER_SLEEP -> Caught <ctrl>+<c>"; I=$COUNT' 2
+  trap 'echo ; echo "Skipping ETHER_SLEEP -> Caught <ctrl>+<c>" ; I=$COUNT' INT
 
   I=0
   while [ $I -lt $COUNT ]; do
@@ -142,6 +142,9 @@ count_loop() {
     echo -n "$I "
     sleep 1
   done
+
+  trap INT
+
   echo
 }
 #
@@ -209,7 +212,164 @@ flamethrower_client() {
     
 
     # build command
-    UDP_RECEIVER_OPTIONS="--interface ${DEVICE} --portbase $PORTBASE --nokbd"
+    UDP_RECEIVER_OPTIONS="--interface ${DEVICE} --portbase $PORTBASE"
+    if [ ! -z $TTL ]; then
+        UDP_RECEIVER_OPTIONS="$UDP_RECEIVER_OPTIONS --ttl $TTL"
+    fi
+    if [ "$NOSYNC" = "on" ]; then
+        UDP_RECEIVER_OPTIONS="$UDP_RECEIVER_OPTIONS --nosync"
+    fi
+    if [ "$ASYNC" = "on" ]; then
+        UDP_RECEIVER_OPTIONS="$UDP_RECEIVER_OPTIONS --async"
+    fi
+    if [ ! -z $MCAST_ALL_ADDR ]; then
+        UDP_RECEIVER_OPTIONS="$UDP_RECEIVER_OPTIONS --mcast-all-addr $MCAST_ALL_ADDR"
+    fi
+
+    # Which tar opts should we use?  If our tar has --overwrite capability, use it.
+    #   Summary: busybox tar doesn't (boel_binaries and prior).
+    #            Debian patched gnu tar does (image and on).
+    #            We want this option enabled for the image to ensure proper directory
+    #            permissions. -BEF-
+    tar --help 2>&1 | grep -q overwrite && TAR_OPTS='--overwrite -xp' || TAR_OPTS='-x'
+
+
+    # set vars
+    [ -z $RETRY ] && RETRY=0
+    COUNT=0
+    FLAMETHROWER_CLIENT_SLEEP=3
+    unset TAR_EXIT_STATUS
+    TAR_EXIT_FILE=/tmp/tar_exit
+    UDP_RECEIVER_STDERR_LOG="/tmp/udp-receiver.${MODULE_NAME}"
+    TAR_STDERR_LOG=/tmp/tar.stderr.log
+
+
+
+    # loop
+    until [ "$TAR_EXIT_STATUS" = "0" ]
+    do
+        # launch udp-receiver
+        if [ -z $UDP_RECEIVER_RUNNING ]; then
+
+            UDP_RECEIVER_RUNNING=1
+
+            rm -f $UDP_RECEIVER_STDERR_LOG $TAR_STDERR_LOG
+            echo TAR_EXIT_STATUS= > $TAR_EXIT_FILE
+
+            echo
+            echo "flamethrower_client(${MODULE_NAME})"
+            echo '--------------------------------------------------------------------------------'
+            echo "udp-receiver $UDP_RECEIVER_OPTIONS 2>${UDP_RECEIVER_STDERR_LOG} | tar ${TAR_OPTS} -C ${DIR} 2>$TAR_STDERR_LOG"
+            ( 
+                udp-receiver $UDP_RECEIVER_OPTIONS 2>${UDP_RECEIVER_STDERR_LOG} | tar ${TAR_OPTS} -C ${DIR} 2>$TAR_STDERR_LOG
+                echo "TAR_EXIT_STATUS=$?" > $TAR_EXIT_FILE
+             ) &
+        fi    
+        
+
+        # test udp-receiver log file
+        if [ -e $UDP_RECEIVER_STDERR_LOG ]; then
+            grep -q '^Transfer complete' $UDP_RECEIVER_STDERR_LOG && COMPLETED=yes || COMPLETED=no
+            grep -q ^bytes $UDP_RECEIVER_STDERR_LOG && STARTED=yes || STARTED=no
+
+            if [ "$COMPLETED" = "yes" ]; then
+                # Cool!  Let's proceed
+                [ ! -z $DEBUG ] && echo COMPLETED=yes
+            elif [ "$STARTED" = "yes" ]; then
+                THIS_STAMP=`ls -l $UDP_RECEIVER_STDERR_LOG`
+                [ ! -z $DEBUG ] && echo
+                [ ! -z $DEBUG ] && echo LAST $LAST_STAMP
+                [ ! -z $DEBUG ] && echo THIS $THIS_STAMP
+                if [ "$THIS_STAMP" = "$LAST_STAMP" ]; then
+                    echo "WARNING: No progress since last check.  Killing udp-receiver."
+                    while killall -9 udp-receiver; do sleep 1; done
+                    unset UDP_RECEIVER_RUNNING
+                    sleep 5
+                fi
+                LAST_STAMP=$THIS_STAMP
+            fi
+
+        fi
+
+
+        # test exit status from tar command
+        . $TAR_EXIT_FILE
+
+        if [ "$TAR_EXIT_STATUS" = "" ]; then
+            # just proceed, no worries
+        elif [ "$TAR_EXIT_STATUS" = "0" ]; then
+            # success -- break loop, and proceed with install
+            break
+        else
+            # failure
+            if [ $COUNT -lt $RETRY ]; then
+                COUNT=$(( $COUNT + 1 ))
+                echo "flamethrower_client: Proceeding with retry $COUNT of $RETRY"
+            else
+                echo "flamethrower_client: FATAL: Initial attempt and $RETRY retries failed!"
+                shellout
+            fi
+        fi
+
+
+        # sleep apnea
+        echo -n "Waiting for cast to begin"
+        sleep_loop $FLAMETHROWER_CLIENT_SLEEP
+
+    done
+
+    # done
+    echo "done!"
+    echo 'flamethrower_client: Success!'
+
+
+    # Unset vars, so next module (which may not have them set) won't use then unintentially
+    unset TTL
+    unset NOSYNC
+    unset ASYNC
+    unset MCAST_ALL_ADDR
+    unset RETRY
+    unset COUNT
+    unset DIR
+    unset UDP_RECEIVER_RUNNING
+    unset PORTBASE
+
+}
+#
+################################################################################
+#
+# Usage: 
+#
+#   MODULE_NAME=my_module   # Required
+#   DIR=/my/destination/dir # Required
+#  [RETRY=7]                # Optional
+#  [PORTBASE=9000]          # Required if a sourceable file called $MODULE_NAME
+#                           # doesn't exist
+#
+#   flamethrower_client_new  /* we can implement this once udp-receiver can exit properly, and timeout on it's own -BEF- */
+#
+flamethrower_client_new() {
+
+    local COMPLETED STARTED THIS_STAMP LAST_STAMP TAR_STDERR_LOG TAR_OPTS
+
+    # validate
+    if [ -z $PORTBASE ]; then
+        . ${FLAMETHROWER_DIRECTORY_DIR}/${MODULE_NAME}
+        if [ $? != 0 ]; then
+            echo You must either set PORTBASE, or have a sourceable file called
+            echo ${FLAMETHROWER_DIRECTORY_DIR}/MODULE_NAME
+            shellout
+        fi
+    fi
+    if [ -z $DIR ]; then
+        echo Must set DIR
+    else
+        mkdir -p $DIR
+    fi
+    
+
+    # build command
+    UDP_RECEIVER_OPTIONS="--interface ${DEVICE} --portbase $PORTBASE"
     if [ ! -z $TTL ]; then
         UDP_RECEIVER_OPTIONS="$UDP_RECEIVER_OPTIONS --ttl $TTL"
     fi
@@ -235,7 +395,7 @@ flamethrower_client() {
     [ -z $RETRY ] && RETRY=0
     COUNT=0
     FLAMETHROWER_CLIENT_SLEEP=3
-    unset UDP_RECEIVER_EXIT_STATUS
+    UDP_RECEIVER_EXIT_STATUS=
 
     # example udp-receiver command:
     #   udp-receiver --interface lo --portbase 9002 --nosync --nokbd --pipe 'tar --overwrite -xp -C  /tmp/.flamethrower.12298'
@@ -249,16 +409,20 @@ flamethrower_client() {
         echo
         echo "flamethrower_client(${MODULE_NAME})"
         echo '--------------------------------------------------------------------------------'
-        echo "udp-receiver $UDP_RECEIVER_OPTIONS --pipe 'tar ${TAR_OPTS} -C ${DIR}'"
+
         # Create script to do tar stuff.  Can't seem to get the tar command escaped properly for direct use 
         # with --pipe.  For example, --pipe 'tar --overwrite -xp -C  /tmp/.flamethrower.12298' fails. -BEF-
-        echo '#!/bin/sh'                    > /tmp/tar_cmd.sh
-        echo "tar ${TAR_OPTS} -C ${DIR}"    >> /tmp/tar_cmd.sh
-        chmod 755 /tmp/tar_cmd.sh
-set -x
-        udp-receiver $UDP_RECEIVER_OPTIONS --pipe /tmp/tar_cmd.sh
+        echo '#!/bin/sh'                       >  /tmp/tar_cmd.${MODULE_NAME}.sh
+        echo "tar ${TAR_OPTS} -C ${DIR}"       >> /tmp/tar_cmd.${MODULE_NAME}.sh
+        chmod 755                                 /tmp/tar_cmd.${MODULE_NAME}.sh
+
+        echo "udp-receiver $UDP_RECEIVER_OPTIONS --pipe /tmp/tar_cmd.${MODULE_NAME}.sh"
+        udp-receiver $UDP_RECEIVER_OPTIONS --pipe /tmp/tar_cmd.${MODULE_NAME}.sh
         UDP_RECEIVER_EXIT_STATUS=$?
-set +x
+        echo
+        echo
+        echo "exit status: $UDP_RECEIVER_EXIT_STATUS"
+        echo
 
         # proceed or retry based on exit status
         if [ "$UDP_RECEIVER_EXIT_STATUS" != "0" ]; then
