more bug fixes, clean up
 * got rid of all external file requirements
 * added inetd/xinetd entries for atftpd
 * fixed bug where tftp entry wasn't always being added to inetd.conf
 * fixed bug where superservers weren't always being reloaded
 * added pxelinux questions/options

diff --git a/sbin/mkbootserver b/sbin/mkbootserver
--- a/sbin/mkbootserver
+++ b/sbin/mkbootserver
@@ -16,22 +16,293 @@ LOCAL_DHCP=""
 KERNEL=""
 INITRD=""
 TFTPDIR=""
+PXELINUX=""
 
 usage="\
 Usage:  netbootconf.sh [-f] [--interface=interface] [--localdhcp=y|n] 
-	[--kernel=path] [--initrd=path] [--tftpdir=dir]"
+	[--kernel=path] [--initrd=path] [--tftpdir=dir] [--pxelinux=path]"
        
 PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 
-DISTRO="unknown"
-PKGDIR="./pkgs"
-CONFIG_DIR="./configs"
-
 TFTPD_PATH=""
-
 TFTP_TEST_FILE_TEXT="all your tftp test file are belong to us"
+TFTP_DAEMON=""
 
 program_name=`basename $0`
+
+SYSLINUX_DEFAULT="\
+DEFAULT kernel
+APPEND vga=extended load_ramdisk=1 prompt_ramdisk=0 initrd=initrd.gz root=/dev/ram rw
+DISPLAY message.txt
+PROMPT 1
+TIMEOUT 50"
+
+PXE_CONF="\
+#  *******  PXE CONFIGURATION FILE *******
+# Any Line starting with a '#\" is treated as a comment line
+# and ignored. However, '#' must be the first character on
+# a line and no spaces before that are allowed.
+
+
+# The following entry is the name of the interface on which pxe is going
+# to operate. We use this interface to get the ip address automatically.
+
+[Network_Interface_Name]
+eth0
+
+
+# The following entry will be queried if PXE fails to get 
+# the IP address automatically through 'ifconfig' like code built-in. This
+# is only needed if the above interface name is not present in the system
+
+
+[OurIpAddress]
+#192.215.100.202
+
+
+# This entry shows the base directory of the mtftpd. All file names/paths
+# will be relative to this directory. This is the same name that should 
+# be used as the start up argument to the mtftpd daemon.
+
+[Mtftpd_Root_Directory]
+/tftpboot
+
+
+# Set the following entry to 0 if you have a DHCP server running on this 
+# system.
+
+[UseDHCPPort]
+1
+
+
+# Set the entry below to zero if you don't want this system to act 
+# as a PXE proxyDHCP
+
+[StartProxy]
+1
+
+
+# Set the entry below to zero if you don't want this system to act as a 
+# PXE boot server
+
+[startBootService]
+1
+
+
+[MasterProxy]
+1
+
+
+# 0 - broadcast discovery is enabled; 1 - broadcast discovery is disabled
+
+[Discovery_BCast_Disabled]
+0
+
+
+# 0 - multicast discovery is enabled; 1 - multicast discovery is disabled
+
+[Discovery_MCast_Disabled]
+0
+
+
+# Multicast Discovery address. The boot server would listen on this address 
+# for multicast boot server packets.
+
+[Discovery_MCast_Addr]
+224.0.1.2
+
+
+# Prompt to display on the user screen
+# format of this entry: timeout,<string>
+
+[Prompt]
+10,Press F8 to view menu ...
+
+
+# This entry is set to 1 if the client should accept only responses
+# from servers in this list
+
+[Discovery_Server_List_Only]
+0
+
+
+# the format of the discovery_list entry is as follows
+# type of the server, # of entries, Ip address of each entry 
+# separated by commas
+
+[Discovery_List]
+#3,2,192.215.100.49,192.215.100.99
+#65535,1,192.215.100.45
+
+
+# In some systems, the all '1' broadcast address 255.255.255.255 
+# won't work as the system will fail with a network unreachable message.
+# In those cases, you can use the 'route add -host 255.255.255.255 eth0' 
+# command to add a route. Or else, you can define the host portion of the 
+# address alone as '1' in the following entry. This entry is not 
+# required if your system is set up to transmit
+# broadcast packets on 255.255.255.255
+
+[Broadcast_ip_address]
+#192.215.100.255
+
+
+# Architectures supported
+# format : <arch-type>,<arch-string>
+
+[PROC_ARCH]
+0,X86PC
+
+
+# Boot server types supported
+
+[Service_Types]
+0,BStrap
+13,linux-install
+# 14,linux-boot
+
+
+# Menu string that will be displayed on the client screen
+# after F8 is pressed.
+[X86PC/UNDI/MENU]
+0,Local Boot
+13,Remote Install Linux
+# 14,Remote Boot Linux
+
+
+# Image file name for Linux install boot server type
+# format : <min layer #> <max layer #> <base file name>
+[X86PC/UNDI/linux-install/ImageFile_Name]
+0
+2
+linux
+
+
+# Image file name for Linux boot server type
+# format : <min layer #> <max layer #> <base file name>
+# [X86PC/UNDI/linux-boot/ImageFile_Name]
+# 0
+# 2
+# linux
+
+
+# Image file name for BStrap boot server
+# format : <min layer #> <max layer #> <base file name>
+
+[X86PC/UNDI/BStrap/ImageFile_Name]
+0
+0
+bstrap
+
+
+# List of plug-ins. The PXEClientTester is the plug-in that
+# validates received packets for PXE compliance. By default, this
+# plug-in is DISBALED. Remove the '#\" in front of it, if you want
+# packet validation to happen
+
+[Parsers]
+# PXEClientTester
+PxeParser
+
+
+[Parsers/PxeParser/MainFunction]
+PxeParser
+
+
+[Parsers/PxeParser/DllPath]
+/usr/lib/libpxeParser.so
+
+
+[Parsers/PXEClientTester/MainFunction]
+PXEClientTester
+
+
+[Parsers/PXEClientTester/DllPath]
+/usr/lib/libpxeTester.so
+
+
+# Even if the PXEClientTester is loaded, you still need to
+# turn this flag to '1' for packet validation.
+
+[TestOn]
+1
+
+
+# Directory where the results of the packet validation by PXEClientTester
+# will be written to. Under this directory, there will be 
+# sub-directories with the last 8 digits of the MAc address of
+# each client.
+
+[TestPath]
+/tmp
+
+
+# Option DLL for BStrap
+
+[X86PC/UNDI/BStrap/Vendor_Dll]
+/usr/lib/libBstrapOpts.so
+
+
+# Fill in a NT server name that will be contacted by the client
+# to log back in for APitest
+
+[ServerName]
+#vviswana-desk2
+
+
+# Specify whether the above server is in a domain or a workgroup
+
+[IsDomain]
+0
+
+
+# specify the name of the workgroup or domain of the server
+
+[Domain]
+starwars
+
+
+# All debug related stuff here
+
+
+# If this entry is set to 1, pxe services will write
+# more debug info to the system log using syslog()
+
+[DEBUG/PxeServices_DebugOutToWindow_On]
+0
+
+
+# If this entry is set to 1, pxe parser will write
+# more debug info to the system log using syslog()
+
+[DEBUG/PxeParsers_DebugOutToWindow_On]
+0
+
+# If this entry is set to 1, pxe services will write
+# more debug info to the file mentioned
+# under the entry [DEBUG/PxeServices_Debug_FileName]
+
+[DEBUG/PxeServices_DebugOutToFile_On]
+0
+
+
+# If this entry is set to 1, pxe parser will write
+# more debug info to the file mentioned
+# under the entry [DEBUG/PxeParsers_Debug_FileName]
+
+[DEBUG/PxeParsers_DebugOutToFile_On]
+0
+
+
+[DEBUG/PxeServices_Debug_FileName]
+/PxeServiceLog.txt
+
+
+[DEBUG/PxeParsers_Debug_FileName]
+/PxeParserLog.txt
+
+
+[End]"
 
 ### BEGIN BACKUP_FILE()
 ############################################################
@@ -166,44 +437,54 @@ check_atftpd() {
 
 ### BEGIN CONFIGURE INETD FOR TFTPD_HPA
 configure_inetd_for_tftpd_hpa() {
-    # Debian has a nice tool to take care of this.  Does this work for xinetd?
-    if [ "$DISTRO" == "Debian" ]; then
+    if [ "$TFTP_DAEMON" == "tftpd-hpa" ]; then
+	inetd_entry="tftp\tdgram\tudp\twait.100\troot\t/usr/sbin/tcpd\tin.tftpd -s -r blksize $TFTPDIR"
+	tftp_xinetd="$TFTP_HPA_XINETD"
+    elif [ "$TFTP_DAEMON" == "atftpd" ]; then
+	inetd_entry="tftp\tdgram\tudp\twait\tnobody\t/usr/sbin/tcpd\t/usr/sbin/in.tftpd --tftpd-timeout 300  --retry-timeout 5 --maxthread 100 --verbose=5 --logfile /var/log/atftpd.log $TFTPDIR"
+	tftp_xinetd="$ATFTP_XINETD"
+    else
+	echo "Unrecognized tftp server, cannot create an inetd entry."
+    fi
+
+    ### BEGIN LOOK FOR SUPERSERVER
+    echo -n "Checking for a running inetd... "
+    inetd_pid=`ps -C inetd | grep inetd | cut -c 0-5`
+    if [ "$inetd_pid" == "" ]; then
+	echo "Not found."
+    else
+	echo "$inetd_pid."
+    fi
+    echo -n "Checking for a running xinetd... "
+    xinetd_pid=`ps -C xinetd | grep xinetd | cut -c 0-5`
+    if [ "$xinetd_pid" == "" ]; then
+	echo "Not found."
+    else
+	echo "$xinetd_pid."
+    fi
+    ### END LOOK FOR SUPERSERVER
+
+    echo -n "Looking for update-inetd... "
+    which update-inetd 1> /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+	echo "found."
+	# Debian has a tool for this.  Does this work for xinetd?
 	echo -n "Updating inetd.conf... "
-	update-inetd --remove "^tftp.*"
-	update-inetd --group BOOT --add \
-	    "tftp\tdgram\tudp\twait.100\troot\t/usr/sbin/tcpd\tin.tftpd -s -r blksize $TFTPDIR"
+	update-inetd --remove "^#?tftp.*"
+	update-inetd --group BOOT --add "$inetd_entry"
 	echo "done."
     else
-	echo -n "Checking for a running inetd... "
-	inetd_pid=`ps -C inetd | grep inetd | cut -c 0-5`
-	if [ "$inetd_pid" == "" ]; then
-	    echo "Not found."
-	else
-	    echo "$inetd_pid."
-	fi
-	echo -n "Checking for a running xinetd... "
-	xinetd_pid=`ps -C xinetd | grep xinetd | cut -c 0-5`
-	if [ "$xinetd_pid" == "" ]; then
-	    echo "Not found."
-	else
-	    echo "$xinetd_pid."
-	fi
-
-	# configure inetd
+	echo "not found."
+	
+	### BEGIN CONFIGURE INETD
 	if [ "$inetd_pid" != "" ]; then
 	    sed s/"^[[:space:]]*tftp"/"#tftp"/ < /etc/inetd.conf > /tmp/$program_name.inetd.conf
 	    mv /etc/inetd.conf /etc/inetd.conf.$program_name.bak
 	    mv /tmp/$program_name.inetd.conf /etc/inetd.conf
-	    echo -e "tftp\tdgram\tudp\twait.100\troot\t/usr/sbin/tcpd\tin.tftpd -s -r blksize $TFTPDIR" >> /etc/inetd.conf
-	    echo -n "Sending a SIGHUP to inetd (pid $inetd_pid)... "
-	    kill -HUP $inetd_pid
-	    if [ $? -ne 0 ]; then
-		echo "failed."
-		return 1
-	    fi
-	    echo "done."
+	    echo -e "$inetd_entry" >> /etc/inetd.conf
+	### END CONFIGURE INETD
 	    
-	# configure xinetd
+	### BEGIN CONFIGURE XINETD
 	elif [ "$xinetd_pid" != "" ]; then
 	    grep "includedir[[:space:]*]/etc/xinetd.d" /etc/xinetd.conf 1> /dev/null 2> /dev/null
 	    if [ $? -ne 0 ]; then
@@ -217,21 +498,38 @@ configure_inetd_for_tftpd_hpa() {
 		return 1
 	    fi
 
-	    cp -a $CONFIG_DIR/tftp /etc/xinetd.d/tftp
-	    echo "Sending SIGUSR1 to xinetd... "
-	    kill -USR1 $xinetd_pid
-	    if [ $? -eq 0 ]; then
-		echo "done."
-	    else
-		echo "failed."
-		return 1
-	    fi
+	    echo "${tftp_xinetd}" > /etc/xinetd.d/tftp
+	### END CONFIGURE XINETD
 	else
 	    echo "I couldn't find a running inetd or xinetd."
 	    echo "Nothing to configure."
 	    return 1
 	fi
     fi
+
+    ### BEGIN RELOAD SUPERSERVER
+    if [ "$inetd_pid" != "" ]; then
+	echo -n "Sending a SIGHUP to inetd (pid $inetd_pid)... "
+	kill -HUP $inetd_pid
+	if [ $? -ne 0 ]; then
+	    echo "failed."
+	    return 1
+	fi
+	echo "done."
+    elif [ "$xinetd_pid" != "" ]; then
+	echo "Sending SIGUSR1 to xinetd... "
+	kill -USR1 $xinetd_pid
+	if [ $? -eq 0 ]; then
+	    echo "done."
+	else
+	    echo "failed."
+	    return 1
+	fi
+    else
+	echo "No superserver found, so nothing to reload"
+    	return 1
+    fi
+    ### END RELOAD SUPERSERVER
 }
 ### END CONFIGURE INETD FOR TFTPD_HPA
 
@@ -339,12 +637,13 @@ install_pxe_daemon() {
 	return 0
     else
 	echo "not found."
-	echo ""
+	echo "****************************************************************"
 	echo "I couldn't find a pxe daemon on your system.  For RedHat"
 	echo "systems, you can install the pxe RPM for your release.  For"
 	echo "Debian systems, you can try one of the debs i've built from the"
 	echo "RedHat package source.  These packages should be available from"
 	echo "http://dannf.org/"
+	echo "****************************************************************"
 	return 1
     fi
 }
@@ -359,7 +658,7 @@ configure_pxe_daemon() {
 	return 1
     fi
 
-    cp -a $CONFIG_DIR/pxe.conf /etc
+    echo "${PXE_CONF}" > /etc/pxe.conf
 
     ### BEGIN edit /etc/pxe.conf
     if [ "$INTERFACE" != "" ]; then
@@ -482,23 +781,40 @@ pxelinux_cfg() {
 	fi
     fi
     
-    echo -n "Copying $CONFIG_DIR/syslinux.cfg to $LINUX_INSTALL/pxelinux.cfg/..."
-    cp -a $CONFIG_DIR/default $LINUX_INSTALL/pxelinux.cfg
+    echo "${SYSLINUX_DEFAULT}" > $LINUX_INSTALL/pxelinux.cfg/default
     if [ $? -ne 0 ]; then
 	echo "failed."
 	return 1
     fi
     echo "done."
-    
-    if [ ! -f $PKGDIR/pxelinux.0 ]; then
-	echo "Couldn't find $PKGDIR/pxelinux.0"
+
+    if [ -z "$PXELINUX" ]; then
+	echo -n "What is the path to the pxelinux bootloader [/usr/lib/syslinux/pxelinux.0]? "
+	if [ "$INTERACTIVE" == "no" ]; then
+	    REPLY=""
+	    echo "Non-interactive mode, assuming default."
+	else
+	    read REPLY
+	fi
+	if [ "$REPLY" == "" ]; then
+	    PXELINUX="/usr/lib/syslinux/pxelinux.0"
+	else
+	    PXELINUX=$REPLY
+	fi
+    fi
+    if [ ! -f "$PXELINUX" ]; then
+	echo "$PXELINUX does not exist or is not a regular file."
+	return 1
+    fi	
+    if [ ! -f $PXELINUX ]; then
+	echo "Couldn't find $PXELINUX"
 	return 1
     fi
 
     ### BEGIN BACKUP EXISTING PXELINUX.BIN
     if [ -a $LINUX_INSTALL/linux.0 ]; then
 	if [ "`md5sum $LINUX_INSTALL/linux.0` != \
-			`md5sum $PKGDIR/pxelinux.0`" ]; then
+			`md5sum $PXELINUX`" ]; then
             echo "$LINUX_INSTALL/linux.0 already exists, but doesn't match the pxelinux.0 I want to install."
 
 	    FILE_TO_BACKUP=$LINUX_INSTALL/linux.0
@@ -512,8 +828,8 @@ pxelinux_cfg() {
 
     ### BEGIN COPY OVER PXELINUX.BIN
     if [ ! -a $LINUX_INSTALL/linux.0 ]; then
-	echo -n "Copying $PKGDIR/pxelinux.0 to $LINUX_INSTALL/linux.0 ... "
-	cp -a $PKGDIR/pxelinux.0 $LINUX_INSTALL/linux.0
+	echo -n "Copying $PXELINUX to $LINUX_INSTALL/linux.0 ... "
+	cp -a $PXELINUX $LINUX_INSTALL/linux.0
 	if [ $? -ne 0 ]; then
 	    echo "failed."
 	    return 1
@@ -696,6 +1012,8 @@ while [ $# -gt 0 ]; do
 	--kernel=* )       KERNEL="`echo \"${1}\" | sed -e 's/^[^=]*=//'`" ; shift ;;
 	--initrd=* )       INITRD="`echo \"${1}\" | sed -e 's/^[^=]*=//'`" ; shift ;;
 	--tftpdir=* )      TFTPDIR="`echo \"${1}\" | sed -e 's/^[^=]*=//'`" ; shift ;;
+	--pxelinux=* )     PXELINUX="`echo \"${1}\" | sed -e 's/^[^=]*=//'`" ; shift ;;
+	
 	* ) echo "${usage}" 1>&2; exit 1 ;;
     esac
 done
@@ -721,7 +1039,7 @@ if [ "$TFTPDIR" == "" ]; then
     echo -n "Where should tftpd serve files from ([/tftpboot]? "
     if [ "$INTERACTIVE" == "no" ]; then
 	REPLY=""
-	echo "Non-interactive mode, taking the default"
+	echo "Non-interactive mode, taking the default."
     else
 	read REPLY
     fi
@@ -762,6 +1080,40 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+TFTP_HPA_XINETD="\
+# default: off
+# description: The tftp server serves files using the trivial file transfer
+# 	protocol.  The tftp protocol is often used to boot diskless
+#	workstations, download configuration files to network-aware printers,
+#	and to start the installation process for some operating systems.
+service tftp
+{
+        socket_type             = dgram
+        protocol                = udp
+        wait                    = yes
+        user                    = root
+        server                  = `which in.tftpd`
+        server_args             = -s $TFTPDIR -r blksize
+        disable                 = no
+}"
+
+ATFTP_XINETD="\
+# default: off
+# description: The tftp server serves files using the trivial file transfer
+# 	protocol.  The tftp protocol is often used to boot diskless
+#	workstations, download configuration files to network-aware printers,
+#	and to start the installation process for some operating systems.
+service tftp
+{
+        socket_type             = dgram
+        protocol                = udp
+        wait                    = yes
+        user                    = root
+        server                  = `which in.tftpd`
+        server_args             = --tftpd-timeout 300  --retry-timeout 5 --maxthread 100 --verbose=5 --logfile /var/log/atftpd.log $TFTPDIR
+        disable                 = no
+}"
+
 # check to see if the installed tftpd is one
 # of the ones that is known to support options
 # necessary for PXE booting.
@@ -770,7 +1122,11 @@ if [ $? -ne 0 ]; then
     check_atftpd
     if [ $? -ne 0 ]; then
 	exit 1
+    else
+	TFTP_DAEMON="atftpd"
     fi
+else
+    TFTP_DAEMON="tftpd-hpa"
 fi
 
 configure_inetd_for_tftpd_hpa
@@ -818,5 +1174,3 @@ if [ `which makedhcpserver` != "" ]; then
 	    * ) makedhcpserver ;;
     esac
 fi
-
-
