fix: /etc/init.d scripts correctly return success of failure for starting/stopping services

diff --git a/etc/init.d/systemimager-server-flamethrowerd b/etc/init.d/systemimager-server-flamethrowerd
--- a/etc/init.d/systemimager-server-flamethrowerd
+++ b/etc/init.d/systemimager-server-flamethrowerd
@@ -57,12 +57,23 @@ case "$1" in
     fi
     echo -n "Starting Flamethrower daemon: flamethrowerd"
     flamethrowerd --config-file /etc/systemimager/flamethrower.conf --pid-file $PPID_FILE
-    echo "."
+    if [ $? -eq 0 ]; then
+        echo "ok."
+    else
+        echo "failed."
+        exit 1
+    fi
     ;;
   stop)
     echo -n "Stopping Flamethrower daemon: flamethrowerd"
     kill_em_all
-    echo
+    if ps -p `cat $PPID_FILE 2>/dev/null` >/dev/null 2>&1; then
+        echo "failed."
+        exit 1
+    else
+        echo "ok."
+        exit 0
+    fi
     ;;
   status)
     echo -n "Status of Flamethrower daemon: flamethrowerd... "
diff --git a/etc/init.d/systemimager-server-monitord b/etc/init.d/systemimager-server-monitord
--- a/etc/init.d/systemimager-server-monitord
+++ b/etc/init.d/systemimager-server-monitord
@@ -62,18 +62,25 @@ EOF
     else
         $SI_MONITOR 0>/dev/null >&0 2>&0 &
     fi
-    if [ $? -ne 0 ]; then
-        echo failed.
-        exit 1
+    if ps -p `cat $PIDFILE 2>/dev/null` >/dev/null 2>&1; then
+        echo "ok."
     else
-        echo ok.
+        echo "failed."
+        exit 1
     fi
     ;;
   stop)
     echo -n "Stopping SystemImager's installation monitoring: si_monitor... "
     [ -f $PIDFILE ] && kill `cat $PIDFILE` >/dev/null 2>&1
-    rm -f $PIDFILE
-    echo "stopped."
+    if [ $? -eq 0 ]; then
+        rm -f $PIDFILE
+        echo "stopped."
+        exit 0
+    else
+        rm -f $PIDFILE
+        echo "failed."
+        exit 1
+    fi
     ;;
   status)
     echo -n "Status of SystemImager's installation monitoring: si_monitor... "
diff --git a/etc/init.d/systemimager-server-netbootmond b/etc/init.d/systemimager-server-netbootmond
--- a/etc/init.d/systemimager-server-netbootmond
+++ b/etc/init.d/systemimager-server-netbootmond
@@ -34,14 +34,26 @@ PIDFILE=/var/run/si_netbootmond.pid
 
 case "$1" in
   start)
-    echo -n "Starting SystemImager's net boot client monitor: si_netbootmond"
+    echo -n "Starting SystemImager's net boot client monitor: "
     si_netbootmond
-    echo "."
+    if pgrep si_netbootmond >/dev/null 2>&1; then
+        echo "ok."
+        exit 0
+    else
+        echo "failed."
+        exit 1
+    fi
     ;;
   stop)
-    echo -n "Stopping SystemImager's net boot client monitor: si_netbootmond"
-    [ -f $PIDFILE ] && kill `cat $PIDFILE`
-    echo "."
+    echo -n "Stopping SystemImager's net boot client monitor: "
+    [ -f $PIDFILE ] && kill `cat $PIDFILE 2>/dev/null`
+    if [ $? -eq 0 ]; then
+        echo "ok."
+        exit 0
+    else
+        echo "failed."
+        exit 1
+    fi
     ;;
   status)
     echo -n "Status of SystemImager's net boot client monitor: si_netbootmond... "
diff --git a/etc/init.d/systemimager-server-rsyncd b/etc/init.d/systemimager-server-rsyncd
--- a/etc/init.d/systemimager-server-rsyncd
+++ b/etc/init.d/systemimager-server-rsyncd
@@ -45,13 +45,25 @@ case "$1" in
 	PID=`pgrep -f "$DAEMON $OPTIONS"`
 	[ ! -z "$PID" ] && echo "already running." && exit 0
 	$DAEMON $OPTIONS
-	echo "$NAME."
+	if ps -p $PID >/dev/null 2>&1; then
+		echo "ok."
+		exit 0
+	else
+		echo "failed."
+		exit 1
+	fi
 	;;
   stop)
 	echo -n "Stopping $DESC: "
-	PID=`pidof $NAME`
+	PID=`pgrep -f "$DAEMON $OPTIONS"`
 	[ ! -z "$PID" ] && kill $PID
-	echo "$NAME."
+	if [ $? -eq 0 ]; then
+		echo "stopped."
+		exit 0
+	else
+		echo "failed."
+		exit 1
+	fi
 	;;
   status)
 	echo -n "Status of rsync daemon for systemimager: "
@@ -70,4 +82,3 @@ case "$1" in
 	;;
 esac
 
-exit 0
