merging unstable-2_1_x -> HEAD

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -8,9 +8,11 @@
 # This is the debhelper compatability version to use.
 export DH_COMPAT=2
 
+ARCH = $(shell uname -m | sed -e s/i.86/i386/ -e s/sun4u/sparc64/ -e s/arm.*/arm/ -e s/sa110/arm/)
+
 TFTP_DIR = /usr/lib/systemimager
 
-#OVERRIDE_PKGS := systemimager-server systemimager-kernel-i386 systemimager-initrd-i386 systemimager-bin-i386
+#OVERRIDE_PKGS := systemimager-server systemimager-kernel-$(ARCH) systemimager-initrd-$(ARCH) systemimager-bin-$(ARCH)
 
 configure: configure-stamp
 configure-stamp:
@@ -24,6 +26,10 @@ build-stamp:
 	dh_testdir
 
 	# Add here commands to compile the package.
+	@[ "$(ARCH)" == "i386" ] || [ "$(ARCH)" == "ia64" ] || \
+	 (echo -e "\n\n********** Error **********" && \
+	  echo "Only i386 and ia64 clients are supported in this release." && \
+	  echo -e "You must build on one of these systems\n" && exit 1 )
 	$(MAKE) docs
 	cp CHANGE.LOG changelog
 
@@ -36,10 +42,9 @@ clean:
 
 	# Add here commands to clean up after the build process.
 	-$(MAKE) distclean
-#	-$(MAKE) clean
 	-rm -rf debian/systemimager-client debian/systemimager-server \
-	debian/systemimager-kernel-i386 debian/systemimager-initrd-i386 \
-	debian/systemimager-bin-i386
+	debian/systemimager-kernel-$(ARCH) debian/systemimager-initrd-$(ARCH) \
+	debian/systemimager-bin-$(ARCH)
 	-rm -f $(CURDIR)/changelog
 	dh_clean
 
@@ -55,9 +60,8 @@ install: build
 
 	mkdir -p debian/systemimager-server
 	$(MAKE) install_server DESTDIR=$(CURDIR)/debian/systemimager-server
+	$(MAKE) check_floppy_size
 	mkdir -p $(CURDIR)/debian/systemimager-server/etc/systemimager
-#	install -m 644 $(CURDIR)/debian/config \
-#		$(CURDIR)/debian/systemimager-server/etc/systemimager
 
 	mkdir -p debian/systemimager-common
 	$(MAKE) install_common DESTDIR=$(CURDIR)/debian/systemimager-common
@@ -65,16 +69,16 @@ install: build
 	mkdir -p debian/systemimager-doc
 	$(MAKE) install_docs DESTDIR=$(CURDIR)/debian/systemimager-doc
 
-	mkdir -p debian/systemimager-kernel-i386
-	$(MAKE) install_kernel DESTDIR=$(CURDIR)/debian/systemimager-kernel-i386
+	mkdir -p debian/systemimager-kernel-$(ARCH)
+	$(MAKE) install_kernel DESTDIR=$(CURDIR)/debian/systemimager-kernel-$(ARCH)
 
-	mkdir -p debian/systemimager-initrd-i386
-	$(MAKE) install_initrd DESTDIR=$(CURDIR)/debian/systemimager-initrd-i386
+	mkdir -p debian/systemimager-initrd-$(ARCH)
+	$(MAKE) install_initrd DESTDIR=$(CURDIR)/debian/systemimager-initrd-$(ARCH)
 
-	mkdir -p debian/systemimager-bin-i386
-	$(MAKE) install_raidtools DESTDIR=$(CURDIR)/debian/systemimager-bin-i386
-	$(MAKE) install_reiserfsprogs DESTDIR=$(CURDIR)/debian/systemimager-bin-i386
-
+	mkdir -p debian/systemimager-bin-$(ARCH)
+	$(MAKE) install_raidtools DESTDIR=$(CURDIR)/debian/systemimager-bin-$(ARCH)
+	$(MAKE) install_reiserfsprogs DESTDIR=$(CURDIR)/debian/systemimager-bin-$(ARCH)
+	$(MAKE) install_dosfstools DESTDIR=$(CURDIR)/debian/systemimager-bin-$(ARCH)
 
 	# install lintian overrides
 
diff --git a/sbin/mkbootserver b/sbin/mkbootserver
--- a/sbin/mkbootserver
+++ b/sbin/mkbootserver
@@ -3,9 +3,8 @@
 #
 #   $Id$
 #
-#  Copyright (C) dann frazier <dannf@dannf.org>
+#   Written by Dann Frazier <daniel_frazier@hp.com>
 #
-
 
 #########################################################################
 # The intent of this script is to automate the configuration of a
@@ -25,7 +24,7 @@ INITRD=""
 TFTPDIR=""
 PXELINUX=""
 
-program_name=`basename $0`
+program_name=$(basename $0)
 
 usage="\
 Usage:  $program_name [-f] [--interface=interface] [--localdhcp=y|n] 
@@ -37,12 +36,14 @@ TFTPD_PATH=""
 TFTP_TEST_FILE_TEXT="all your tftp test file are belong to us"
 TFTP_DAEMON=""
 
-SYSLINUX_DEFAULT="\
-DEFAULT kernel
-APPEND vga=extended load_ramdisk=1 prompt_ramdisk=0 initrd=initrd.gz root=/dev/ram rw
-DISPLAY message.txt
-PROMPT 1
-TIMEOUT 50"
+CONFIG_DIR="/etc/systemimager"
+
+#SYSLINUX_DEFAULT="\
+#DEFAULT kernel
+#APPEND vga=extended load_ramdisk=1 prompt_ramdisk=0 initrd=initrd.gz root=/dev/ram rw
+#DISPLAY message.txt
+#PROMPT 1
+#TIMEOUT 50"
 
 PXE_CONF="\
 #  *******  PXE CONFIGURATION FILE *******
@@ -524,8 +525,8 @@ configure_inetd_for_tftpd_hpa() {
 	fi
 	echo "done."
     elif [ "$xinetd_pid" != "" ]; then
-	echo "Sending SIGUSR1 to xinetd... "
-	kill -USR1 $xinetd_pid
+	echo "Sending SIGUSR2 to xinetd... "
+	kill -USR2 $xinetd_pid
 	if [ $? -eq 0 ]; then
 	    echo "done."
 	else
@@ -649,7 +650,7 @@ install_pxe_daemon() {
 	echo "systems, you can install the pxe RPM for your release.  For"
 	echo "Debian systems, you can try one of the debs i've built from the"
 	echo "RedHat package source.  These packages should be available from"
-	echo "http://dannf.org/"
+	echo "http://dannf.org/systemimager"
 	echo "****************************************************************"
 	return 1
     fi
@@ -690,7 +691,7 @@ configure_pxe_daemon() {
     fi
     
     echo -n "Checking to make sure $interface is up... "
-    ifconfig $interface | grep "inet addr" 1> /dev/null 2> /dev/null
+    ifconfig $interface | grep "inet" 1> /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
 	echo "yup."
     else
@@ -788,7 +789,13 @@ pxelinux_cfg() {
 	fi
     fi
     
-    echo "${SYSLINUX_DEFAULT}" > $LINUX_INSTALL/pxelinux.cfg/default
+    cp -f ${CONFIG_DIR}/pxelinux.cfg/syslinux.cfg $LINUX_INSTALL/pxelinux.cfg/default
+    if [ $? -ne 0 ]; then
+	echo "failed."
+	return 1
+    fi
+
+    cp -f ${CONFIG_DIR}/pxelinux.cfg/message.txt $LINUX_INSTALL/pxelinux.cfg/message.txt
     if [ $? -ne 0 ]; then
 	echo "failed."
 	return 1
